-- Migration 052: Portfolio Chat Sessions
-- Stores conversation history for the Portfolio AI Chat feature.
-- One row per session (upserted on conversation end).
-- On next visit: show summary card + inject last messages as context.

CREATE TABLE IF NOT EXISTS portfolio_chat_sessions (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    broker_account_id  UUID NOT NULL REFERENCES broker_accounts(id) ON DELETE CASCADE,

    -- Brief human-readable summary of what was discussed (max 300 chars)
    -- Generated by the last LLM response or extracted from conversation
    summary            VARCHAR(500),

    -- Full message list as JSONB array: [{role, content, timestamp}]
    -- Capped at last 30 messages to keep storage bounded
    messages           JSONB NOT NULL DEFAULT '[]',

    -- When this conversation started and ended
    started_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at           TIMESTAMPTZ,

    -- Message count for quick display
    message_count      INTEGER NOT NULL DEFAULT 0,

    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One active session per account (most recent)
CREATE INDEX IF NOT EXISTS idx_portfolio_chat_sessions_account
    ON portfolio_chat_sessions(broker_account_id, started_at DESC);

COMMENT ON TABLE portfolio_chat_sessions IS
    'Portfolio AI Chat conversation history. Shows flashback card on next visit.';
COMMENT ON COLUMN portfolio_chat_sessions.messages IS
    'JSONB array of {role, content, timestamp}. Capped at 30 messages.';
