"""
Zerodha Console tradebook import.

WHY THIS EXISTS
---------------
Kite Connect cannot give us trade history. Per the official docs
(https://kite.trade/docs/connect/v3/orders/):

    "This API returns a list of all trades generated by all executed orders
     for the day."
    "The order history or the order book is transient as it only lives for a
     day in the system."

So a new subscriber connects and we know nothing about them — every
history-dependent surface (Analytics, Edge/Leak, My Patterns, quality scores)
is blank until they have traded with us for weeks. The only route to real
history is the CSV the user can download from Console → Reports → Tradebook.

DESIGN NOTES
------------
* One CSV row = one FILL (it carries both trade_id and order_id). That maps
  exactly onto how this codebase already stores fills: `Trade.order_id` holds
  the trade_id and `Trade.kite_order_id` holds the order id (see
  trade_sync_service._map_trade_fields). So the existing unique constraint
  `uq_trades_broker_order (broker_account_id, order_id)` gives us idempotency
  for free — re-uploading an overlapping date range cannot duplicate rows.

* The exact header spelling of the Console export is NOT publicly documented
  and has changed over time, so parsing is tolerant: the header row is located
  by scanning, columns are matched through an alias map, and unknown columns
  are ignored rather than fatal.

* Console timestamps are IST; everything downstream stores UTC.

* Bad rows are collected and reported, never abort the whole import — a single
  malformed row in a 3-year export must not cost the user their history.
"""

from __future__ import annotations

import csv
import io
import logging
import re
from datetime import datetime, time, timezone
from typing import Any, Dict, Iterable, List, Optional, Tuple
from zoneinfo import ZoneInfo

logger = logging.getLogger(__name__)

IST = ZoneInfo("Asia/Kolkata")

# Hard ceiling. A 3-year F&O tradebook is realistically well under this; the cap
# exists so a malicious or corrupt file cannot exhaust memory.
MAX_ROWS = 200_000
# How far down the file to look for the header row before giving up.
HEADER_SCAN_LIMIT = 25

# Canonical field -> accepted header spellings (normalised: lowercase, spaces and
# underscores collapsed). Extend freely; unknown columns are ignored.
_ALIASES: Dict[str, Tuple[str, ...]] = {
    "tradingsymbol": ("symbol", "tradingsymbol", "instrument", "scrip", "contract"),
    "isin":          ("isin",),
    "exchange":      ("exchange", "exch"),
    "segment":       ("segment", "seg"),
    "series":        ("series",),
    "trade_type":    ("tradetype", "type", "buysell", "transactiontype", "bs"),
    "quantity":      ("quantity", "qty", "quantitytraded", "filledquantity"),
    "price":         ("price", "avgprice", "averageprice", "tradeprice", "rate"),
    "trade_date":    ("tradedate", "date"),
    "trade_time":    ("orderexecutiontime", "executiontime", "tradetime", "time"),
    "trade_id":      ("tradeid", "tradenumber", "tradeno"),
    "order_id":      ("orderid", "ordernumber", "orderno"),
}

_BUY = {"buy", "b", "bought", "purchase"}
_SELL = {"sell", "s", "sold", "sale"}


def _norm(header: str) -> str:
    """Normalise a header cell for alias matching."""
    return re.sub(r"[\s_\-./]+", "", (header or "").strip().lower())


def _build_column_map(header_cells: List[str]) -> Dict[str, int]:
    """Map canonical field -> column index, using the alias table."""
    mapping: Dict[str, int] = {}
    for idx, cell in enumerate(header_cells):
        key = _norm(cell)
        if not key:
            continue
        for canonical, aliases in _ALIASES.items():
            if canonical in mapping:
                continue
            if key in aliases:
                mapping[canonical] = idx
                break
    return mapping


def _looks_like_header(cells: List[str]) -> Optional[Dict[str, int]]:
    """
    A row is the header if it yields the minimum columns we cannot work without.

    Console exports have carried banner/metadata rows above the real table at
    various times, so the header is found by scanning rather than assumed to be
    row 0.
    """
    mapping = _build_column_map(cells)
    required = ("tradingsymbol", "trade_type", "quantity", "price", "trade_date")
    if all(f in mapping for f in required):
        return mapping
    return None


def _parse_decimal(raw: str) -> Optional[float]:
    if raw is None:
        return None
    cleaned = str(raw).strip().replace(",", "").replace("₹", "")
    if cleaned in ("", "-", "--"):
        return None
    try:
        return float(cleaned)
    except ValueError:
        return None


def _parse_int(raw: str) -> Optional[int]:
    val = _parse_decimal(raw)
    if val is None:
        return None
    return int(abs(val))  # Console may render sells as negative quantities


_DATE_FORMATS = ("%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y", "%Y/%m/%d", "%d-%b-%Y", "%d %b %Y")
_TIME_FORMATS = ("%H:%M:%S", "%H:%M", "%I:%M:%S %p", "%I:%M %p")


def _parse_timestamp(date_raw: str, time_raw: Optional[str]) -> Optional[datetime]:
    """
    Combine Console's date (+ optional execution time) into an aware UTC datetime.

    Console renders IST. When no time column is present the trade is anchored at
    09:15 IST — enough for day-level bucketing, and deliberately NOT midnight,
    which would fall outside market hours and skew hour-of-day analytics.
    """
    d_raw = (date_raw or "").strip()
    t_raw = (time_raw or "").strip()
    if not d_raw and not t_raw:
        return None

    # Console's `order_execution_time` is a FULL timestamp ("2026-07-15 09:32:11"),
    # not a bare time. Try it as a complete datetime first — naively appending it
    # to the date produces "<date> <date> <time>", which parses as nothing and
    # silently falls back to the 09:15 default, flattening every trade into the
    # same hour bucket and destroying all hour-of-day analytics.
    for candidate in (t_raw, d_raw):
        # Only treat it as a self-contained datetime if it actually carries a
        # time. A bare date would otherwise parse here and short-circuit to
        # midnight, skipping both the date+time combination below and the
        # 09:15 market-open default.
        if not candidate or ":" not in candidate:
            continue
        for dfmt in _DATE_FORMATS:
            for tfmt in _TIME_FORMATS:
                try:
                    dt = datetime.strptime(candidate, f"{dfmt} {tfmt}")
                    return dt.replace(tzinfo=IST).astimezone(timezone.utc)
                except ValueError:
                    pass
        try:
            dt = datetime.fromisoformat(candidate)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=IST)
            return dt.astimezone(timezone.utc)
        except ValueError:
            pass

    if not d_raw:
        return None

    # Bare date + bare time in separate columns.
    combined = f"{d_raw} {t_raw}" if t_raw else d_raw

    for dfmt in _DATE_FORMATS:
        for tfmt in _TIME_FORMATS:
            try:
                dt = datetime.strptime(combined, f"{dfmt} {tfmt}")
                return dt.replace(tzinfo=IST).astimezone(timezone.utc)
            except ValueError:
                pass
        # Date alone
        try:
            d = datetime.strptime(d_raw, dfmt).date()
            dt = datetime.combine(d, time(9, 15))
            return dt.replace(tzinfo=IST).astimezone(timezone.utc)
        except ValueError:
            continue

    # ISO-ish fallback
    try:
        dt = datetime.fromisoformat(combined)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=IST)
        return dt.astimezone(timezone.utc)
    except ValueError:
        return None


def _infer_exchange(row_exchange: str, segment: str, tradingsymbol: str) -> str:
    """Best-effort exchange when the column is absent or blank."""
    exch = (row_exchange or "").strip().upper()
    if exch:
        return exch
    seg = (segment or "").strip().upper()
    if seg in ("FO", "F&O", "NFO", "EQUITY_DERIVATIVES"):
        return "NFO"
    if seg in ("CD", "CDS", "CURRENCY"):
        return "CDS"
    if seg in ("MCX", "COM", "COMMODITY"):
        return "MCX"
    sym = (tradingsymbol or "").upper()
    if sym.endswith(("CE", "PE")) or "FUT" in sym:
        return "NFO"
    return "NSE"


class TradebookParseError(Exception):
    """Raised when the file cannot be understood at all."""


def parse_tradebook_csv(content: bytes) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], Dict[str, Any]]:
    """
    Parse a Console tradebook CSV.

    Returns (rows, errors, meta) where `rows` are normalised dicts ready to be
    mapped onto Trade records, `errors` are per-row problems (never fatal), and
    `meta` describes what was detected.
    """
    try:
        text = content.decode("utf-8-sig")
    except UnicodeDecodeError:
        try:
            text = content.decode("latin-1")
        except Exception as e:  # pragma: no cover - defensive
            raise TradebookParseError(f"Could not decode file: {e}") from e

    reader = csv.reader(io.StringIO(text))
    all_rows: List[List[str]] = []
    for i, r in enumerate(reader):
        all_rows.append(r)
        if i > MAX_ROWS + HEADER_SCAN_LIMIT:
            break

    if not all_rows:
        raise TradebookParseError("The file is empty.")

    # ── Locate the header ────────────────────────────────────────────────────
    col_map: Optional[Dict[str, int]] = None
    header_idx = -1
    for idx, cells in enumerate(all_rows[:HEADER_SCAN_LIMIT]):
        found = _looks_like_header(cells)
        if found:
            col_map, header_idx = found, idx
            break

    if col_map is None:
        seen = [c for c in (all_rows[0] if all_rows else []) if str(c).strip()][:12]
        raise TradebookParseError(
            "This does not look like a Zerodha Console tradebook. Expected columns "
            "for symbol, trade type, quantity, price and trade date. "
            f"First row seen: {seen}"
        )

    def cell(cells: List[str], field: str) -> str:
        i = col_map.get(field, -1)
        if i < 0 or i >= len(cells):
            return ""
        return (cells[i] or "").strip()

    rows: List[Dict[str, Any]] = []
    errors: List[Dict[str, Any]] = []
    truncated = False

    for line_no, cells in enumerate(all_rows[header_idx + 1:], start=header_idx + 2):
        if len(rows) >= MAX_ROWS:
            truncated = True
            break
        if not any((c or "").strip() for c in cells):
            continue  # blank line

        symbol = cell(cells, "tradingsymbol")
        ttype_raw = cell(cells, "trade_type").lower()
        qty = _parse_int(cell(cells, "quantity"))
        price = _parse_decimal(cell(cells, "price"))
        ts = _parse_timestamp(cell(cells, "trade_date"), cell(cells, "trade_time") or None)

        problems = []
        if not symbol:
            problems.append("missing symbol")
        if ttype_raw in _BUY:
            transaction_type = "BUY"
        elif ttype_raw in _SELL:
            transaction_type = "SELL"
        else:
            transaction_type = ""
            problems.append(f"unrecognised trade type '{cell(cells, 'trade_type')}'")
        if not qty:
            problems.append("missing or zero quantity")
        if price is None:
            problems.append("missing price")
        if ts is None:
            problems.append(f"unparseable date '{cell(cells, 'trade_date')}'")

        if problems:
            errors.append({"line": line_no, "problems": problems})
            continue

        trade_id = cell(cells, "trade_id")
        order_id = cell(cells, "order_id")
        if not trade_id and not order_id:
            # Without any broker identity we cannot dedupe, and re-importing
            # would silently duplicate. Synthesise a deterministic key from the
            # trade's own content so repeat uploads still collapse.
            trade_id = "syn-" + "-".join([
                symbol, transaction_type, str(qty), f"{price:.4f}", ts.isoformat()
            ])

        rows.append({
            "tradingsymbol": symbol.upper(),
            "exchange": _infer_exchange(cell(cells, "exchange"), cell(cells, "segment"), symbol),
            "segment": cell(cells, "segment") or None,
            "transaction_type": transaction_type,
            "quantity": qty,
            "price": price,
            "timestamp": ts,
            "trade_id": trade_id or order_id,
            "order_id": order_id or trade_id,
            "isin": cell(cells, "isin") or None,
        })

    meta = {
        "header_row": header_idx + 1,
        "columns_detected": sorted(col_map.keys()),
        "data_rows_seen": len(rows) + len(errors),
        "truncated": truncated,
        "row_cap": MAX_ROWS,
    }
    return rows, errors, meta


def to_trade_payload(row: Dict[str, Any]) -> Dict[str, Any]:
    """
    Convert a parsed tradebook row into the same shape
    trade_sync_service._map_trade_fields produces, so the rest of the pipeline
    (FIFO -> completed_trades -> features) is identical for imported and live
    data.

    `order_id` carries the trade_id and `kite_order_id` the order id, matching
    the live sync convention and engaging uq_trades_broker_order for dedupe.
    """
    from app.utils.trade_classifier import classify_trade

    raw = {
        "tradingsymbol": row["tradingsymbol"],
        "exchange": row["exchange"],
        "transaction_type": row["transaction_type"],
        "quantity": row["quantity"],
        "average_price": row["price"],
        "price": row["price"],
        "product": None,          # Console does not export product reliably
        "order_type": "MARKET",
        "status": "COMPLETE",
    }
    try:
        classification = classify_trade(raw)
    except Exception:
        classification = {
            "asset_class": "UNKNOWN",
            "instrument_type": "UNKNOWN",
            "product_type": "NRML",
        }

    ts = row["timestamp"]
    return {
        "order_id": str(row["trade_id"]),
        "kite_order_id": str(row["order_id"]) if row.get("order_id") else None,
        "exchange_order_id": None,
        "tradingsymbol": row["tradingsymbol"],
        "exchange": row["exchange"],
        "instrument_token": None,
        "transaction_type": row["transaction_type"],
        "order_type": "MARKET",
        # Console does not carry product (MIS/NRML/CNC). Classification infers a
        # default; recorded in raw_payload so it is never mistaken for broker truth.
        "product": classification.get("product_type", "NRML"),
        "validity": "DAY",
        "variety": "regular",
        "quantity": row["quantity"],
        "filled_quantity": row["quantity"],
        "pending_quantity": 0,
        "cancelled_quantity": 0,
        "disclosed_quantity": 0,
        "price": row["price"],
        "average_price": row["price"],
        "trigger_price": None,
        "status": "COMPLETE",
        "status_message": None,
        "order_timestamp": ts,
        "exchange_timestamp": ts,
        "fill_timestamp": ts,
        "tag": None,
        "guid": None,
        "parent_order_id": None,
        "asset_class": classification["asset_class"],
        "instrument_type": classification["instrument_type"],
        "product_type": classification["product_type"],
        "segment": row.get("segment"),
        "raw_payload": {
            "source": "console_tradebook_import",
            "isin": row.get("isin"),
            "segment": row.get("segment"),
            "product_inferred": True,
        },
        "pnl": 0.0,
    }
