import { useState, useMemo, useEffect, useCallback } from 'react';
import { Bell, BellOff, CheckCheck, Clock, TrendingUp, Shield } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Skeleton } from '@/components/ui/skeleton';
import { cn } from '@/lib/utils';
import { api } from '@/lib/api';
import { useAlerts, AlertNotification } from '@/contexts/AlertContext';
import { PatternSeverity } from '@/types/patterns';
import AlertDetailSheet from '@/components/alerts/AlertDetailSheet';

// ─── Severity config ──────────────────────────────────────────────────────────

const SEV_DOT: Record<PatternSeverity, string> = {
  critical: 'bg-tm-loss',
  high:     'bg-tm-loss/60',
  medium:   'bg-tm-obs',
  low:      'bg-slate-400',
};
const SEV_LABEL: Record<PatternSeverity, string> = {
  critical: 'Critical',
  high:     'High',
  medium:   'Caution',
  low:      'Info',
};
const SEV_LABEL_COLOR: Record<PatternSeverity, string> = {
  critical: 'text-tm-loss',
  high:     'text-tm-loss',
  medium:   'text-tm-obs',
  low:      'text-muted-foreground',
};
const SEV_LEFT_BORDER: Record<PatternSeverity, string> = {
  critical: 'border-l-tm-loss',
  high:     'border-l-tm-loss',
  medium:   'border-l-tm-obs',
  low:      'border-l-slate-300 dark:border-l-slate-600',
};

function timeAgo(dateStr: string | undefined): string {
  if (!dateStr) return '—';
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  const hrs = Math.floor(mins / 60);
  const days = Math.floor(hrs / 24);
  if (mins < 1)  return 'just now';
  if (mins < 60) return `${mins}m ago`;
  if (hrs < 24)  return `${hrs}h ago`;
  return `${days}d ago`;
}

function formatIST(dateStr: string | undefined): string {
  if (!dateStr) return '—';
  return new Date(dateStr).toLocaleString('en-IN', {
    timeZone: 'Asia/Kolkata',
    month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

// ─── Alert row ────────────────────────────────────────────────────────────────

function AlertRow({
  alert,
  onOpen,
}: {
  alert: AlertNotification;
  onOpen: (alert: AlertNotification) => void;
}) {
  const sev = alert.pattern.severity;

  return (
    <button
      onClick={() => onOpen(alert)}
      aria-label={`${alert.pattern.name} — ${SEV_LABEL[sev]}${alert.acknowledged ? ', reviewed' : ', unreviewed'}`}
      className={cn(
        'tm-card w-full text-left transition-colors hover:bg-muted/20',
        alert.acknowledged && 'opacity-60',
      )}
    >
      <div className="flex items-start gap-3 px-4 py-4">
        <span className={cn('flex-shrink-0', SEV_DOT[sev])}
          style={{ width: 3, height: 20, minWidth: 3, borderRadius: 2, marginTop: 2 }}
        />

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap mb-1">
            <span className="text-[13px] font-semibold text-foreground">{alert.pattern.name}</span>
            <span className={cn('text-[10px] font-semibold uppercase tracking-wide', SEV_LABEL_COLOR[sev])}>
              {SEV_LABEL[sev]}
            </span>
            {alert.acknowledged && (
              <span className="text-[10px] text-muted-foreground border border-border rounded px-1.5 py-0.5">
                Reviewed
              </span>
            )}
          </div>

          {/* Evidence line — dynamic, generated by behavior_engine with real trade numbers */}
          <p className="text-[12px] text-muted-foreground leading-relaxed line-clamp-2">
            {alert.pattern.description}
          </p>

          <div className="flex items-center gap-2 mt-1.5 text-[11px] text-muted-foreground">
            <Clock className="h-3 w-3 flex-shrink-0" />
            <span>{timeAgo(alert.shown_at)}</span>
            {(alert.pattern.estimated_cost ?? 0) > 0 && (
              <>
                <span className="text-muted-foreground/40">·</span>
                <span className="text-tm-loss font-mono tabular-nums">
                  ₹{(alert.pattern.estimated_cost as number).toLocaleString('en-IN')} est.
                </span>
              </>
            )}
          </div>
        </div>

        <span className="text-muted-foreground/40 text-[11px] flex-shrink-0 mt-0.5">›</span>
      </div>
    </button>
  );
}

// ─── Live Tab ─────────────────────────────────────────────────────────────────

function AlertSkeleton() {
  return (
    <div className="space-y-2.5">
      {[1, 2, 3].map(i => (
        <div key={i} className="tm-card px-4 py-4 flex items-start gap-3">
          <Skeleton className="w-0.5 h-5 rounded flex-shrink-0 mt-0.5" />
          <div className="flex-1 space-y-2">
            <Skeleton className="h-3.5 w-36 rounded" />
            <Skeleton className="h-3 w-full rounded" />
            <Skeleton className="h-3 w-48 rounded" />
          </div>
        </div>
      ))}
    </div>
  );
}

function LiveTab({ onOpen }: { onOpen: (a: AlertNotification) => void }) {
  const { alerts, isLoading, acknowledgeAll } = useAlerts();
  const live = useMemo(
    () => alerts
      .filter(a => !a.acknowledged)
      .sort((a, b) => new Date(b.shown_at ?? 0).getTime() - new Date(a.shown_at ?? 0).getTime()),
    [alerts]
  );

  if (isLoading) return <AlertSkeleton />;

  if (live.length === 0) {
    return (
      <div className="tm-card px-5 py-6 flex items-start gap-4">
        <div className="w-8 h-8 rounded-full bg-teal-50 dark:bg-teal-900/20 flex items-center justify-center flex-shrink-0 mt-0.5">
          <Shield className="h-4 w-4 text-tm-brand" />
        </div>
        <div>
          <p className="text-[13px] font-semibold text-foreground">Clean session</p>
          <p className="text-[12px] text-muted-foreground mt-0.5 leading-relaxed">
            No active behavioral alerts. You're trading with discipline — keep it up.
          </p>
          <p className="text-[11px] text-muted-foreground/60 mt-2">
            Alerts appear here as they fire. Check History to review past patterns.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-2.5">
      <div className="flex items-center justify-between">
        <p className="text-[12px] text-muted-foreground">
          {live.length} unreviewed alert{live.length !== 1 ? 's' : ''} · tap to open
        </p>
        <button
          onClick={acknowledgeAll}
          className="flex items-center gap-1.5 text-[11px] text-muted-foreground hover:text-foreground transition-colors"
        >
          <CheckCheck className="h-3.5 w-3.5" />
          Mark all reviewed
        </button>
      </div>
      {live.map(alert => (
        <AlertRow key={alert.id} alert={alert} onOpen={onOpen} />
      ))}
    </div>
  );
}

// ─── History Tab ──────────────────────────────────────────────────────────────

const SEVERITY_OPTIONS = [
  { value: 'all',      label: 'All' },
  { value: 'critical', label: 'Critical' },
  { value: 'high',     label: 'High' },
  { value: 'medium',   label: 'Caution' },
  { value: 'low',      label: 'Info' },
];

const PERIOD_OPTIONS = [
  { label: '7d',  hours: 168  },
  { label: '30d', hours: 720  },
  { label: '90d', hours: 2160 },
] as const;

function HistoryTab({ onOpen }: { onOpen: (a: AlertNotification) => void }) {
  // History has its own data source — loads independently of AlertContext
  // so users can see alerts beyond the 7-day live window.
  const [hours, setHours] = useState(168);
  const [sevFilter, setSevFilter] = useState('all');
  const [allAlerts, setAllAlerts] = useState<AlertNotification[]>([]);
  const [loading, setLoading] = useState(true);

  const loadHistory = useCallback(async (h: number) => {
    setLoading(true);
    try {
      const res = await api.get('/api/risk/alerts', { params: { hours: h } });
      const raw = res.data.alerts ?? [];
      // Use the same shape AlertContext uses — map raw to AlertNotification
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const mapped: AlertNotification[] = raw.map((a: any) => ({
        id: String(a.id),
        pattern: {
          id:                  String(a.id),
          type:                a.pattern_type,
          backend_type:        a.pattern_type,
          name:                a.pattern_type.split('_').map((w: string) => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
          severity:            ({'danger':'high','critical':'critical','high':'high','caution':'medium','medium':'medium','low':'low'} as Record<string,PatternSeverity>)[a.severity] ?? 'medium',
          description:         a.message,
          detected_at:         a.detected_at || a.created_at,
          insight:             a.details?.insight || '',
          historical_insight:  a.details?.historical_insight || '',
          estimated_cost:      (a.details?.estimated_cost as number) ?? 0,
          trades_involved:     [],
          frequency_this_week:  0,
          frequency_this_month: 0,
          details:             a.details ?? {},
        },
        shown_at:     a.detected_at || a.created_at,
        acknowledged: a.acknowledged ?? (a.acknowledged_at != null),
      }));
      mapped.sort((a, b) => new Date(b.shown_at ?? 0).getTime() - new Date(a.shown_at ?? 0).getTime());
      setAllAlerts(mapped);
    } catch {
      setAllAlerts([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { loadHistory(hours); }, [hours, loadHistory]);

  const filtered = useMemo(
    () => sevFilter === 'all' ? allAlerts : allAlerts.filter(a => a.pattern.severity === sevFilter),
    [allAlerts, sevFilter]
  );

  return (
    <div className="space-y-4">
      {/* Controls row */}
      <div className="flex items-center gap-3 flex-wrap">
        {/* Period selector */}
        <div className="flex items-center gap-0.5 p-0.5 bg-slate-100 dark:bg-neutral-700/50 rounded-lg">
          {PERIOD_OPTIONS.map(opt => (
            <button
              key={opt.hours}
              onClick={() => setHours(opt.hours)}
              aria-pressed={hours === opt.hours}
              className={cn(
                'px-3 py-1 text-[11px] font-medium rounded-md transition-all',
                hours === opt.hours
                  ? 'bg-white dark:bg-neutral-800 text-foreground shadow-sm'
                  : 'text-muted-foreground hover:text-foreground'
              )}
            >
              {opt.label}
            </button>
          ))}
        </div>

        {/* Severity filter */}
        <div className="flex items-center gap-0.5 p-0.5 bg-slate-100 dark:bg-neutral-700/50 rounded-lg">
          {SEVERITY_OPTIONS.map(opt => (
            <button
              key={opt.value}
              onClick={() => setSevFilter(opt.value)}
              aria-pressed={sevFilter === opt.value}
              className={cn(
                'px-3 py-1 text-[11px] font-medium rounded-md transition-all',
                sevFilter === opt.value
                  ? 'bg-white dark:bg-neutral-800 text-foreground shadow-sm'
                  : 'text-muted-foreground hover:text-foreground'
              )}
            >
              {opt.label}
            </button>
          ))}
        </div>

        {!loading && (
          <p className="text-[11px] text-muted-foreground ml-auto">
            {filtered.length} alert{filtered.length !== 1 ? 's' : ''}
          </p>
        )}
      </div>

      {loading ? <AlertSkeleton /> : filtered.length === 0 ? (
        <div className="tm-card flex flex-col items-center justify-center py-12 text-center">
          <BellOff className="h-8 w-8 text-muted-foreground/30 mb-3" />
          <p className="text-sm text-muted-foreground">
            {allAlerts.length === 0 ? 'No alerts in this period' : 'No alerts match this filter'}
          </p>
        </div>
      ) : (
        <div className="space-y-2">
          {filtered.map(alert => (
            <AlertRow key={alert.id} alert={alert} onOpen={onOpen} />
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Patterns Tab ─────────────────────────────────────────────────────────────

interface PatternSummary {
  type: string;
  name: string;
  count: number;
  totalCost: number;
  latestAt: string | undefined;
  severities: Record<PatternSeverity, number>;
  worstSeverity: PatternSeverity;
}

const SEVERITY_ORDER: PatternSeverity[] = ['critical', 'high', 'medium', 'low'];

function PatternsTab() {
  const { alerts, isLoading } = useAlerts();

  const summaries = useMemo<PatternSummary[]>(() => {
    const map = new Map<string, PatternSummary>();
    for (const alert of alerts) {
      const key = alert.pattern.type;
      const existing = map.get(key) ?? {
        type: key,
        name: alert.pattern.name,
        count: 0,
        totalCost: 0,
        latestAt: undefined,
        severities: { critical: 0, high: 0, medium: 0, low: 0 },
        worstSeverity: 'low' as PatternSeverity,
      };
      existing.count++;
      existing.totalCost += alert.pattern.estimated_cost ?? 0;
      existing.severities[alert.pattern.severity]++;
      const dt = alert.shown_at;
      if (!existing.latestAt || (dt && dt > existing.latestAt)) existing.latestAt = dt;
      const idx = SEVERITY_ORDER.indexOf(alert.pattern.severity);
      if (idx < SEVERITY_ORDER.indexOf(existing.worstSeverity)) existing.worstSeverity = alert.pattern.severity;
      map.set(key, existing);
    }
    return Array.from(map.values()).sort((a, b) => b.count - a.count);
  }, [alerts]);

  if (isLoading) return <AlertSkeleton />;

  if (summaries.length === 0) {
    return (
      <div className="tm-card flex flex-col items-center justify-center py-16 text-center">
        <TrendingUp className="h-8 w-8 text-muted-foreground/30 mb-3" />
        <p className="text-sm font-medium text-foreground">No pattern data yet</p>
        <p className="text-sm text-muted-foreground mt-1">Patterns appear here as the engine detects behaviors</p>
      </div>
    );
  }

  const maxCount = Math.max(...summaries.map(x => x.count));

  return (
    <div className="space-y-2.5">
      <p className="text-[12px] text-muted-foreground">
        {summaries.length} distinct pattern{summaries.length !== 1 ? 's' : ''} detected in the last 48 hours
      </p>
      {summaries.map(s => (
        <div key={s.type} className={cn('tm-card border-l-2 px-4 py-3.5', SEV_LEFT_BORDER[s.worstSeverity])}>
          <div className="flex items-start justify-between gap-3 mb-2.5">
            <div className="flex items-center gap-2 min-w-0">
              <span className={cn('w-2 h-2 rounded-full flex-shrink-0', SEV_DOT[s.worstSeverity])} />
              <span className="text-[13px] font-semibold text-foreground">{s.name}</span>
              <span className={cn('text-[10px] font-semibold uppercase', SEV_LABEL_COLOR[s.worstSeverity])}>
                {SEV_LABEL[s.worstSeverity]}
              </span>
            </div>
            <div className="text-right flex-shrink-0">
              <span className="text-[18px] font-bold font-mono tabular-nums text-foreground">{s.count}</span>
              <span className="text-[11px] text-muted-foreground ml-1">×</span>
            </div>
          </div>

          {/* Frequency bar */}
          <div className="w-full bg-slate-100 dark:bg-neutral-700/40 rounded-full h-1 mb-2.5">
            <div
              className={cn('h-1 rounded-full transition-all', SEV_DOT[s.worstSeverity])}
              style={{ width: `${Math.min((s.count / maxCount) * 100, 100)}%` }}
            />
          </div>

          <div className="flex items-center justify-between text-[11px] text-muted-foreground">
            <div className="flex items-center gap-2">
              {(SEVERITY_ORDER as PatternSeverity[]).map(sev => s.severities[sev] > 0 && (
                <span key={sev} className="flex items-center gap-1">
                  <span className={cn('w-1.5 h-1.5 rounded-full', SEV_DOT[sev])} />
                  {s.severities[sev]} {sev}
                </span>
              ))}
            </div>
            <div className="flex items-center gap-3">
              {s.totalCost > 0 && (
                <span className="text-tm-loss font-mono tabular-nums">₹{s.totalCost.toLocaleString('en-IN')} est.</span>
              )}
              {s.latestAt && (
                <span title={formatIST(s.latestAt)}>Last: {timeAgo(s.latestAt)}</span>
              )}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function AlertsPage() {
  const { alerts, unacknowledgedCount, acknowledgeAlert } = useAlerts();
  const [selectedAlert, setSelectedAlert] = useState<AlertNotification | null>(null);

  const stats = useMemo(() => ({
    total:    alerts.length,
    critical: alerts.filter(a => a.pattern.severity === 'critical').length,
    high:     alerts.filter(a => a.pattern.severity === 'high').length,
    unacked:  unacknowledgedCount,
  }), [alerts, unacknowledgedCount]);

  return (
    <div className="max-w-3xl mx-auto pb-12">
      {/* Page header */}
      <div className="mb-5 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <h1 className="t-heading-lg text-foreground">Behavioral Alerts</h1>
          {unacknowledgedCount > 0 && (
            <span className="bg-tm-loss text-white text-[10px] font-bold px-1.5 py-0.5 rounded-full leading-none">
              {unacknowledgedCount}
            </span>
          )}
        </div>
        {/* Inline stat strip */}
        {stats.total > 0 && (
          <div className="flex items-center gap-3 text-[12px] text-muted-foreground">
            <span>{stats.total} total</span>
            {stats.critical > 0 && <><span className="text-muted-foreground/40">·</span><span className="text-tm-loss">{stats.critical} critical</span></>}
            {stats.high > 0 && <><span className="text-muted-foreground/40">·</span><span className="text-tm-loss/70">{stats.high} high</span></>}
            {stats.unacked > 0 && <><span className="text-muted-foreground/40">·</span><span className="text-tm-obs">{stats.unacked} unread</span></>}
          </div>
        )}
      </div>

      {/* Tabs */}
      <Tabs defaultValue="live">
        <TabsList className="w-full justify-start rounded-none bg-transparent border-b border-border p-0 h-auto gap-0 mb-6">
          {([
            { value: 'live',     label: 'Live',     badge: unacknowledgedCount },
            { value: 'history',  label: 'History',  badge: 0 },
            { value: 'patterns', label: 'Patterns', badge: 0 },
          ] as const).map(({ value, label, badge }) => (
            <TabsTrigger
              key={value}
              value={value}
              className="relative rounded-none bg-transparent border-b-2 border-transparent px-4 py-2.5 text-sm text-muted-foreground hover:text-foreground transition-colors data-[state=active]:border-tm-brand data-[state=active]:bg-transparent data-[state=active]:text-foreground data-[state=active]:shadow-none"
            >
              {label}
              {badge > 0 && (
                <span className="ml-1.5 bg-tm-loss text-white text-[9px] font-bold px-1.5 py-0.5 rounded-full leading-none">
                  {badge}
                </span>
              )}
            </TabsTrigger>
          ))}
        </TabsList>

        <TabsContent value="live"><LiveTab onOpen={setSelectedAlert} /></TabsContent>
        <TabsContent value="history"><HistoryTab onOpen={setSelectedAlert} /></TabsContent>
        <TabsContent value="patterns"><PatternsTab /></TabsContent>
      </Tabs>

      {/* Alert detail sheet */}
      <AlertDetailSheet
        alert={selectedAlert}
        open={selectedAlert !== null}
        onClose={() => setSelectedAlert(null)}
        onAcknowledge={acknowledgeAlert}
      />
    </div>
  );
}
