import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const LAST_UPDATED = '17 March 2026';
const COMPANY = 'TradeMentor AI';
const CONTACT_EMAIL = 'privacy@tradementor.ai';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12">
        {/* Back link */}
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          Back
        </Link>

        <h1 className="text-3xl font-semibold text-foreground mb-2">Privacy Policy</h1>
        <p className="text-sm text-muted-foreground mb-10">
          Last updated: {LAST_UPDATED} &nbsp;·&nbsp; Compliant with the Digital Personal Data
          Protection Act, 2023 (DPDP Act)
        </p>

        <div className="prose prose-sm max-w-none space-y-8 text-foreground">

          {/* 1. Overview */}
          <section>
            <h2 className="text-lg font-semibold mb-3">1. Overview</h2>
            <p className="text-muted-foreground leading-relaxed">
              {COMPANY} ("we", "us", "our") is committed to protecting your personal data. This
              Privacy Policy explains what data we collect, how we use it, and your rights under
              the Digital Personal Data Protection Act, 2023 (DPDP Act) and other applicable
              Indian law. By using the Platform, you consent to the data practices described below.
            </p>
          </section>

          {/* 2. Data We Collect */}
          <section>
            <h2 className="text-lg font-semibold mb-3">2. Data We Collect</h2>

            <h3 className="text-base font-medium mb-2 mt-4">2.1 Data from Your Broker (via Zerodha KiteConnect API)</h3>
            <p className="text-muted-foreground mb-2">
              When you connect your Zerodha account, we receive and store:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
              <li>Your Zerodha user ID, display name, and registered email address</li>
              <li>Trade and order history (instrument, quantity, price, timestamp, P&L)</li>
              <li>Open and closed positions</li>
              <li>Account-level funds and margin data (read-only, used for risk calculations)</li>
              <li>GTT (Good Till Triggered) orders</li>
            </ul>
            <p className="text-muted-foreground mt-2 text-sm">
              <strong>We do not store your Zerodha password or API secret.</strong> Authentication
              uses Zerodha's OAuth 2.0 flow. We store an encrypted access token solely to fetch
              data on your behalf.
            </p>

            <h3 className="text-base font-medium mb-2 mt-4">2.2 Data You Provide</h3>
            <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
              <li>Trading profile (experience level, trading style, risk tolerance)</li>
              <li>Risk management settings (daily loss limit, max trades, position sizing)</li>
              <li>Journal entries (free-text notes and structured fields you fill in)</li>
              <li>Guardian contact (name and phone number, if you enable Guardian Mode)</li>
              <li>Notification preferences</li>
            </ul>

            <h3 className="text-base font-medium mb-2 mt-4">2.3 Data Generated by the Platform</h3>
            <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
              <li>Detected behavioural patterns and risk alerts</li>
              <li>AI coach conversation history (stored locally on your device by default)</li>
              <li>Daily reports and morning briefings</li>
              <li>Web push notification subscription (endpoint and keys, not personal data)</li>
            </ul>

            <h3 className="text-base font-medium mb-2 mt-4">2.4 Technical Data</h3>
            <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
              <li>Server logs (IP address, user agent, request IDs) for security and debugging</li>
              <li>Error and performance data sent to Sentry (anonymised where possible)</li>
            </ul>
          </section>

          {/* 3. How We Use Your Data */}
          <section>
            <h2 className="text-lg font-semibold mb-3">3. How We Use Your Data</h2>
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-muted">
                  <th className="text-left p-3 border border-border font-medium">Purpose</th>
                  <th className="text-left p-3 border border-border font-medium">Legal Basis (DPDP Act)</th>
                </tr>
              </thead>
              <tbody className="text-muted-foreground">
                {[
                  ['Provide behavioural analytics and pattern detection', 'Consent / Contract performance'],
                  ['Power the AI trading coach with your actual data', 'Consent'],
                  ['Send behavioural alerts, push notifications, WhatsApp/email reports', 'Consent'],
                  ['Display your trading history and P&L analytics', 'Contract performance'],
                  ['Detect and prevent fraud, abuse, or API misuse', 'Legitimate interest / Legal obligation'],
                  ['Improve the Platform and fix bugs', 'Legitimate interest'],
                  ['Comply with legal obligations (including SEBI directives if applicable)', 'Legal obligation'],
                ].map(([purpose, basis], i) => (
                  <tr key={i} className="border-b border-border">
                    <td className="p-3 border border-border">{purpose}</td>
                    <td className="p-3 border border-border">{basis}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          {/* 4. AI Processing */}
          <section>
            <h2 className="text-lg font-semibold mb-3">4. AI Coach & LLM Processing</h2>
            <p className="text-muted-foreground leading-relaxed">
              When you interact with the AI coach, a summary of your recent trading behaviour
              (trade counts, P&L ranges, detected patterns) is sent to our AI provider
              (OpenRouter, which routes to models like Anthropic Claude or OpenAI GPT) to generate
              a response. <strong>We do not send raw trade order IDs, exact timestamps, or
              personally identifiable broker data to the AI provider</strong> — only aggregated
              behavioural summaries are included in the AI prompt.
            </p>
            <p className="text-muted-foreground mt-2 leading-relaxed">
              Conversation data sent to the AI provider is used solely for generating your
              response and is not used to train their models (we use API endpoints, not model
              training programmes). AI responses are retained locally in your browser and on our
              servers only for session continuity.
            </p>
          </section>

          {/* 5. Data Sharing */}
          <section>
            <h2 className="text-lg font-semibold mb-3">5. Data Sharing & Third Parties</h2>
            <p className="text-muted-foreground mb-3">
              We do not sell your personal data. We share data only with:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-muted-foreground">
              <li>
                <strong className="text-foreground">Zerodha Broking Limited</strong> — to
                authenticate you and fetch your trade data via their API
              </li>
              <li>
                <strong className="text-foreground">OpenRouter / AI providers</strong> —
                aggregated behavioural summaries to generate AI coach responses
              </li>
              <li>
                <strong className="text-foreground">Supabase</strong> — our database provider
                (PostgreSQL hosted on AWS); data is encrypted at rest
              </li>
              <li>
                <strong className="text-foreground">Twilio</strong> — if you enable WhatsApp
                alerts; only your phone number and the alert message are sent
              </li>
              <li>
                <strong className="text-foreground">Sentry</strong> — error monitoring; we
                scrub personal data from error reports before sending
              </li>
              <li>
                <strong className="text-foreground">Law enforcement</strong> — if required by
                a court order, SEBI directive, or other legal obligation
              </li>
            </ul>
          </section>

          {/* 6. Data Retention */}
          <section>
            <h2 className="text-lg font-semibold mb-3">6. Data Retention</h2>
            <ul className="list-disc pl-5 space-y-2 text-muted-foreground">
              <li>Trade history and behavioural data: retained for up to 3 years to enable long-term pattern analysis</li>
              <li>Journal entries: retained until you delete them or your account</li>
              <li>Server logs: retained for 90 days, then automatically purged</li>
              <li>Encrypted Zerodha access tokens: deleted immediately on disconnect</li>
              <li>Upon account deletion: all personal data removed within 30 days</li>
            </ul>
          </section>

          {/* 7. Your Rights */}
          <section>
            <h2 className="text-lg font-semibold mb-3">7. Your Rights Under the DPDP Act 2023</h2>
            <p className="text-muted-foreground mb-3">
              As a Data Principal under the DPDP Act 2023, you have the right to:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-muted-foreground">
              <li>
                <strong className="text-foreground">Access</strong> — know what personal data we
                hold about you
              </li>
              <li>
                <strong className="text-foreground">Correction</strong> — request correction of
                inaccurate data
              </li>
              <li>
                <strong className="text-foreground">Erasure</strong> — request deletion of your
                personal data (available in Settings → Danger Zone, or by email)
              </li>
              <li>
                <strong className="text-foreground">Withdraw Consent</strong> — disconnect your
                broker account at any time, which stops all data collection
              </li>
              <li>
                <strong className="text-foreground">Grievance Redressal</strong> — raise a
                complaint with our Data Protection Officer
              </li>
              <li>
                <strong className="text-foreground">Nominate</strong> — nominate another person to
                exercise these rights on your behalf in the event of your death or incapacity
              </li>
            </ul>
            <p className="text-muted-foreground mt-3">
              To exercise any right, email{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline">
                {CONTACT_EMAIL}
              </a>{' '}
              with the subject line "DPDP Request". We will respond within 30 days.
            </p>
          </section>

          {/* 8. Security */}
          <section>
            <h2 className="text-lg font-semibold mb-3">8. Security</h2>
            <p className="text-muted-foreground leading-relaxed">
              We protect your data with industry-standard security measures: TLS encryption in
              transit, AES-256 (Fernet) encryption of broker access tokens at rest, JWT-based
              authentication with short expiry windows, parameterised SQL queries, and
              rate-limiting on all API endpoints. We perform security reviews with each major
              release.
            </p>
            <p className="text-muted-foreground mt-2">
              In the event of a data breach affecting your personal data, we will notify you and
              the relevant authorities as required by applicable law within 72 hours of becoming
              aware of the breach.
            </p>
          </section>

          {/* 9. Cookies */}
          <section>
            <h2 className="text-lg font-semibold mb-3">9. Cookies & Local Storage</h2>
            <p className="text-muted-foreground leading-relaxed">
              We use browser localStorage (not cookies) to store your JWT authentication token
              and app preferences (theme, notification settings, onboarding state). We do not use
              tracking cookies, analytics pixels, or advertising cookies. No third-party cookies
              are set by the Platform.
            </p>
          </section>

          {/* 10. Children */}
          <section>
            <h2 className="text-lg font-semibold mb-3">10. Children's Privacy</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Platform is not intended for persons under 18 years of age. We do not knowingly
              collect data from minors. If we become aware that a minor has provided personal data,
              we will delete it promptly.
            </p>
          </section>

          {/* 11. Changes */}
          <section>
            <h2 className="text-lg font-semibold mb-3">11. Changes to This Policy</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update this Privacy Policy from time to time. Material changes will be
              notified in-app at least 7 days before taking effect. The "Last Updated" date at the
              top of this page always reflects the most recent version.
            </p>
          </section>

          {/* 12. Contact & Grievance */}
          <section>
            <h2 className="text-lg font-semibold mb-3">12. Contact & Grievance Officer</h2>
            <div className="text-muted-foreground space-y-1">
              <p><strong className="text-foreground">Data Protection Officer / Grievance Officer</strong></p>
              <p>{COMPANY}</p>
              <p>
                Email:{' '}
                <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline">
                  {CONTACT_EMAIL}
                </a>
              </p>
              <p className="mt-3 text-sm">
                If you are not satisfied with our response, you may file a complaint with the
                Data Protection Board of India once it is constituted under the DPDP Act 2023.
              </p>
            </div>
          </section>

        </div>

        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-border flex gap-4 text-sm text-muted-foreground">
          <Link to="/terms" className="hover:text-foreground underline">Terms of Service</Link>
          <Link to="/" className="hover:text-foreground">Back to App</Link>
        </div>
      </div>
    </div>
  );
}
